#ifndef _gkg_anatomist_plugin_GkgDwiGlobalTractographyViewer_GlobalTractographyCallbackIds_h_
#define _gkg_anatomist_plugin_GkgDwiGlobalTractographyViewer_GlobalTractographyCallbackIds_h_


#define NOTHING_TO_DO_LABEL            0
#define SPIN_GLASS_CREATION_LABEL      1
#define SPIN_GLASS_DELETION_LABEL      2
#define SPIN_GLASS_RANDOM_MOVE_LABEL   3
#define SPIN_GLASS_OPTIMAL_MOVE_LABEL  4
#define SPIN_GLASS_CONNECTION_LABEL    5


namespace gkg
{


enum GlobalTractographyCallbackId
{

  ANATOMICAL_PRIORS_CALLBACK,

  INITIAL_SPIN_GLASS_CONFIGURATION_CALLBACK,

  SPIN_GLASS_CREATION_CALLBACK,
  SPIN_GLASS_DELETION_CALLBACK,
  SPIN_GLASS_MOVE_CALLBACK,
  SPIN_GLASS_CONNECTION_CREATION_CALLBACK,
  SPIN_GLASS_CONNECTION_DELETION_CALLBACK,

  SPIN_GLASS_CREATION_INFORMATION_CALLBACK,
  SPIN_GLASS_DELETION_INFORMATION_CALLBACK,
  SPIN_GLASS_RANDOM_MOVE_INFORMATION_CALLBACK,
  SPIN_GLASS_OPTIMAL_MOVE_INFORMATION_CALLBACK,
  SPIN_GLASS_CONNECTION_INFORMATION_CALLBACK,
  NOTHING_TO_DO_INFORMATION_CALLBACK

};


}


#endif
