##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 1998  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
##
## Project: NUMARIS/4
##    File: \n4_servers1\pkg\MrServers\MrImaging\seq\GinkgoGradientEcho3d\
##          makefile.trs
## Version: \main\13
##  Author: LANDWIPD
##  Charge: Michael Zwanger, MRIA-Seq, +9131/84-2672
##    Date: 2014-06-02 13:27:08 +02:00
##
##    Lang: make
##
## Descrip: Makefile fuer Sequenz-DLL
##
##-----------------------------------------------------------------------------

##-----------------------------------------------------------------------------
## Naehere Informationen zum den moeglichen Macros im Makefile siehe
## MedMake-Dokumentation Q:/csw/MedMake/html/contents_t6.html
##
NOSYNGO() 

##-----------------------------------------------------------------------------
## enter local compiler flags
##

CPPFLAGS (-D_CONSOLE)
CPPFLAGS (-DBUILD_SEQU)
CPPFLAGS (-DSEQUENCE_CLASS)
# next flag should be the name of the sequence class
CPPFLAGS (-DSEQUENCE_CLASS_GinkgoGradientEcho3d)
CPPFLAGS (-DMRPROT_DEP_OPT)
CPPFLAGS (-DSEQ_NAMESPACE=gkg)

##-----------------------------------------------------------------------------
## enter include paths
##

INCLPATHS (-I /n4_extsw/x86/extsw/MedCom/include)
INCLPATHS (-I /n4/pkg/MrServers/MrImaging/seq/GinkgoLibrary/)

##-----------------------------------------------------------------------------
## enter source files
##

CPPSOURCES(GinkgoGradientEcho3d)
CPPSOURCES(GinkgoGradientEcho3d_UI)

CPPSOURCESFROM(SequenceModule, ../GinkgoLibrary/Core)
CPPSOURCESFROM(SequenceModuleFactory, ../GinkgoLibrary/Core)
CPPSOURCESFROM(ExcitationModule, ../GinkgoLibrary/ExcitationModules)
CPPSOURCESFROM(SingleTxExcitation3dModule, ../GinkgoLibrary/ExcitationModules)
CPPSOURCESFROM(ReadingModule, ../GinkgoLibrary/ReadingModules)
CPPSOURCESFROM(SingleLineReading3dModule, ../GinkgoLibrary/ReadingModules)
CPPSOURCESFROM(SpoilingModule, ../GinkgoLibrary/SpoilingModules)
CPPSOURCESFROM(Spoiling3dModule, ../GinkgoLibrary/SpoilingModules)
CPPSOURCESFROM(EndModule, ../GinkgoLibrary/EndModules)


##-----------------------------------------------------------------------------
## enter link libraries
##

# Base framework
LDLIBS (MrTrace)
LDLIBS (UTrace)
LDLIBS (MrGenericDC)
LDLIBS (MrParc)

# Parameters
LDLIBS (MrProt)
LDLIBS (libSeqSysProp)
LDLIBS (MeasSections)

# Measurement system
#LDLIBS (Sequence)
LDLIBS (libMES)
LDLIBS (MeasNucleiBase)
LDLIBS (libSSL)
# 3D
LDLIBS (MeasNucleiIF)

# Application libraries
LDLIBS (libSBB)
LDLIBS (libSeqUtil)
LDLIBS (libSeqUT)
LDLIBS (libUICtrl)
MSDEV_i586_WinNT400(LDLIBS (libUILink))


##-----------------------------------------------------------------------------
## enter target name
##

LIB(GinkgoGradientEcho3d)

##-----------------------------------------------------------------------------
##  Copyright (C) Siemens AG 1998  All Rights Reserved.  Confidential
##-----------------------------------------------------------------------------
